name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Backend Docker Image
        run: docker buildx build --platform linux/amd64,linux/arm64 -t mvschiranjeevi/backend --push .

      - name: Build Frontend Docker Image
        run: docker buildx build --platform linux/amd64,linux/arm64 -t mvschiranjeevi/frontend --push .

      - name: SSH into EC2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker pull mvschiranjeevi/backend
            docker pull mvschiranjeevi/frontend
            docker run -d --name backend-container -p 4451:4451 mvschiranjeevi/backend
            docker run -d --name frontend-container -p 5173:5173 mvschiranjeevi/frontend
